name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://kit.near.tools
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-mdbook-tools

      - name: Install mdbook tools
        run: |
          cargo install --git https://github.com/r-near/mdbook-llms-txt-tools 
          cargo install mdbook-admonish mdbook-linkcheck
      - name: Build book
        run: mdbook build

      - name: Copy the LLMs txt files
        run: |
          cp llms-txt/llms.txt ./book/html/llms.txt
          cp llms-txt-full/llms-full.txt ./book/html/llms-full.txt

      - name: Deploy to Cloudflare Workers (Static Site)
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "4.47.0"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
